#!/bin/bash

set -euo pipefail

versions=(7.2 7.3)
declare -A roots
roots=([standard-root]=/var/www/html [public-root]=/var/www/html/public)

for version in "${versions[@]}"; do
  for root in "${!roots[@]}"; do
    output_file="${version}-apache/${root}/Dockerfile"

    # Write autogenerated header
    cat dockerfile-header > "$output_file"
    export VERSION=$version
    export APACHE_PUBLIC_FOLDER_CONFIGURATION=${roots[$root]}
    # Append the template
    # We substitute only already defined variables, see https://stackoverflow.com/a/54318029/3641865
    # for more information about the "env | sed" magic
    envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" < Dockerfile.template >> "$output_file"
    # Add modified files
    git add "$output_file"
  done
done

if [[ -n ${GITHUB_WORKFLOW:-} ]]; then
  git config user.email "contact@rezoleo.fr"
  git config user.name "Rézoléo Bot"

  # Commit only if there are differences
  # https://stackoverflow.com/a/8123841
  git diff-index --quiet HEAD || git commit -m "(actions) Updated Dockerfiles"
  git remote set-url --push origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
  git push origin HEAD:"${GITHUB_REF}"
fi
